server:
  port: 9100
spring:
  profiles: dev
  application:
    name: gnw-pub-config-server-dev
  cloud:
    config:
      profile: dev
      server:
        svn:
          uri: https://github.com/letrain/gnw-pub-parent.git
          username: letrain
          password: Hwj38121
          search-paths: '{application}'
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    statusPageUrlPath: ${server.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.info.path:/manager/login/loginIn}
    healthCheckUrlPath: ${server.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.health.path:/health}
    lease-expiration-duration-in-seconds: 15  #续约更新时间间隔
    lease-renewal-interval-in-seconds: 5      #续约到期时间
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
management:
  security:
    enabled: false
encrypt:
  key-store:
    location: config-server.keystore
    alias: config-server
    password: ShemgEnc#@!
    secret: ShemgEnc#@!
security:
  user:
    name: pubuser
    password: pubConfig&^%