server:
  port: 8000
spring:
  application:
    name: gnw-pub-register-server
  cloud:
    config:
      server:
        uri: https://github.com/letrain/gnw-pub-parent.git
        username: letrain
        password: Hwj38121
        search-paths: '{application}'
  rabbitmq:
    host: 172.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    hostname: service-center-2.com
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    statusPageUrlPath: ${server.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.info.path:/manager/login/loginIn}
    healthCheckUrlPath: ${server.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.health.path:/health}
    lease-expiration-duration-in-seconds: 15  #续约更新时间间隔
    lease-renewal-interval-in-seconds: 5      #续约到期时间
  server:
    responseCacheUpdateInvervalMs: 10000     #eureka server刷新readCacheMap的时间
    eviction-interval-timer-in-ms: 5000     #启用主动失效，并且每次主动失效检测间隔为5s
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://172.0.0.1:9000/eureka/
management:
  security:
    enabled: false
