server:
  port: 81
spring:
  application:
    name: gnw-pub-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: gnw-pub-config-server
      fail-fast: true
      retry:
        max-attempts: 6
        multiplier: 1.1
        initial-interval: 1000
        max-interval: 2000
      profile: preprod
  rabbitmq:
    host: 172.16.1.63
    port: 5672
    username: lwpub
    password: '{cipher}AQAaie+CgYgZOh89K2rn1LVfiGq4++vkFBsZPIFMrRMMMjRTvwKrmy68aDXBkQmLokqwoVM/qShpZ7PhrK2hX1FFhdwr0zl2PNt0d0a0YVbPGhSOSrtoxra7cLsBl7g0zTL30BYuYm3Om3+GnEJSY2Sbqh31j4fqWEqYbIcCQM+qnKmriegrPL0GecvRAphRvjgGnGK6+XzH8RD6qIH8F9fLJYQBuBkb+uV0T6ycrCtJNGgQ7n7ei6vCsqNc0TT73d/pt1jKdAQElbZYF/LmiyelkstK/ne2YjmptOhYEI0JjVyxiCi1YRKkEVTZhrb8cesJgTxYzlO1TF5pA8reYhyJUXwtfvIIwZiA50zaEwbqG8vhpoRUrNmOHESdk37B+3k='
    virtual-host: /
  redis:
    database: 0
    host: 172.16.1.62
    port: 6380
    password: lwtx@123
    pool:
      max-total: 32
      max-wait: -1
      max-idle: 32
      min-idle: 8
    timeout: 0
  zipkin:
    base-url: http://172.16.1.64:9300
  sleuth:
    sampler:
      percentage: 0.1
c3p0:
  jdbcUrl: jdbc:mysql://172.16.1.212:3306/user_center?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  user: userdbuser
  password: 1C4uqUp6
  driverClass: com.mysql.jdbc.Driver
  minPoolSize: 10
  maxPoolSize: 100
  maxIdleTime: 60
  acquireIncrement: 3
  initialPoolSize: 5
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  validationQuery: select 'x'
fileutil:
  fileSize: '256MB'
  requestSize: '512MB'
  uploadTmpPath: '/data/project/gateway-upload-tmp'
mybatis:
  mapperLocations : classpath:mybatis/*.xml
logging:
  path: /data/logs/java
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    statusPageUrlPath: ${server.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.info.path:/manager/login/loginIn}
    healthCheckUrlPath: ${server.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.health.path:/health}
    lease-expiration-duration-in-seconds: 15  #续约更新时间间隔
    lease-renewal-interval-in-seconds: 5      #续约到期时间
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://172.16.1.64:9000/eureka/,http://172.16.1.65:9000/eureka/
management:
  security:
    enabled: false      
baseConfig:
  isSignCheck: true
ribbon:
  ReadTimeout: 20000 # 处理时间
  ConnectTimeout: 20000 # 连接时间
  MaxAutoRetries: 0 #最大自动重试次数
  MaxAutoRetriesNextServer: 1 # 换实例重试次数
  MaxTotalHttpConnections: 2000 # 最大http连接数，越大越好，但到到达一个临界点之后，就不会提高响应速度了
  MaxConnectionsPerHost: 1000 # 每个host连接数
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  okhttp:
    enabled: true # 使用okhttp方式请求，正常来说okhttp比较速度快一点
  host:
    max-per-route-connections: 50   # 每个router最大连接数
    max-total-connections: 5000     # 最大连接数
    addHostHeader: true
    socket-timeout-millis: 10000
    connect-timeout-millis: 60000
  ratelimit: #限流
    enabled: true
    repository: REDIS  #对应存储类型（用来存储统计信息）
    behind-proxy: true  #代理之后
    default-policy: #可选 - 针对所有的路由配置的策略，除非特别配置了policies
      limit: 6000 #可选 - 每个刷新时间窗口对应的请求数量限制
#      quota: 1000 #可选-  每个刷新时间窗口对应的请求时间限制（秒）
      refresh-interval: 60 # 刷新时间窗口的时间，默认值 (秒)
      type: #可选 限流方式
#         - user
         - origin
#         - url
  routes:
    file:
      path: /file/**
      serviceId: gnw-file-consumer
    green_wechat:
      path: /wcs/**
      serviceId: greenbox-wechat-consumer
    pay:
      path: /ps/**
      serviceId: gnw-pay-consumer
    payman:
      path: /pm/**
      serviceId: gnw-pay-manager
    schedule:
      path: /sches/**
      serviceId: gnw-schedule-consumer
    gnw_wechat:
      path: /gwcs/**
      serviceId: gnw-wechat-consumer
    pub_order_center:
      path: /poc/**
      url: http://comorder.gwchina.cn/ordercenter
    gnw_location:
      path: /ls/**
      serviceId: gnw-location-consumer
    gnw_push:
      path: /pss/**
      serviceId: gnw-push-consumer
    gnw_greenguard:
      path: /greenguard/**
      serviceId: gnw-greenguard-consumer
    gnw_push_iosmdm:
      path: /ims/**
      serviceId: gnw-push-iosmdm-consumer
    gnw_device:
      path: /ds/**
      serviceId: gnw-device-consumer
    gnw_user:
      path: /us/**
      serviceId: gnw-user-consumer
    gnw_resource:
      path: /rs/**
      serviceId: gnw-resource-consumer
    gnw_im:
      path: /is/**
      serviceId: gnw-im-consumer